### ISSUE TITLE
fullIUrls method needs to be able to skip in-page anchors

### ISSUE THREAD

**Issue by gadgetto** [BobRay/EmailResource#6]
As the `fullUrls` method converts all URLs to full URLs it breaks in-page anchors in emails.
So it would be nice if this method would skip in-page anchor links like this one:

```<a href="#pagefooter">Goto page footer</a>```

https://github.com/BobRay/EmailResource/blob/master/core/components/emailresource/model/emailresource/emailresource.class.php#L136

I tried to play around with the regexes but failed hard ;-)

**Comment by BobRay** [comment]
Would an in-page anchor in an email ever work? I don't see how it could.

**Comment by gadgetto** [comment]
Most email clients supports anchor links very well! If you want to send mails with larger contents you'd probably want to provide a TOC with in-page links.

**Comment by BobRay** [comment]
OK, I get it, but how can the code tell the difference between an in-page href and one linking to another page with an anchor? The second one you would want converted to a full URL.

**Comment by gadgetto** [comment]
Linking to another page + anchor:

```<a href="page.html#jumpto">Link</a>```

Link with in-page anchor only:

```<a href="#jumpto">Link</a>```

So, if href starts with a # it should be simply skipped and not converted to full url!

**Comment by BobRay** [comment]
Got it. Thanks.  

Try replacing the last two sections with these. The second expression should be all on one line with no space between skype) and (([^\:"]).

 /* handle root-relative URLs */
    $html = preg_replace('@\<([^>]*) (href|src)="/([^#"]*)"@i', '<\1 \2="' . $server . '\3"', $html);

    /* handle base-relative URLs */
    $html = preg_replace('@\<([^>]*) (href|src)="(?!#|http|mailto|sip|tel|callto|sms|ftp|sftp|gtalk|skype)(([^\:"])*|([^"]*:[^/"].*))"@i', '<\1 \2="' . $base . '\3"', $html);

**Comment by gadgetto** [comment]
This works - except for this case:

```
<a href="/section1/page1.html#jumpto">Page 1</a>
```

... which leads to (**please note the // after the domain string**):

```
<a href="https://www.domain.com//section1/page1.html#jumpto">Page 1</a>
```

And there is an additional problem if one wants to use URLs without protocol (which is absolutely valid):

```
<a href="//www.xxx.com/page1.html">Page 1</a>
```

... which leads to:

```
<a href="https://www.domain.com//www.xxx.com/page1.html">Page 1</a>
```

**Here is a little test code**:
```
$base = 'https://www.domain.com/';

$html = '<a href="page1.html">Page 1</a>';
echo fullUrls($base, $html).PHP_EOL;

$html = '<a href="section1/page1.html">Page 1</a>';
echo fullUrls($base, $html).PHP_EOL;

$html = '<a href="/section1/page1.html">Page 1</a>';
echo fullUrls($base, $html).PHP_EOL;

$html = '<a href="/section1/page1.html#jumpto">Page 1</a>';
echo fullUrls($base, $html).PHP_EOL;

$html = '<a href="#jumpto">Page 1</a>';
echo fullUrls($base, $html).PHP_EOL;

$html = '<a href="http://www.xxx.com/page1.html">Page 1</a>';
echo fullUrls($base, $html).PHP_EOL;

$html = '<a href="//www.xxx.com/page1.html">Page 1</a>';
echo fullUrls($base, $html).PHP_EOL;

$html = '<img src="folder1/img1.jpg">';
echo fullUrls($base, $html).PHP_EOL;

function fullUrls($base, $html) {
    /* Extract domain name from $base */
    $splitBase = explode('//', $base);
    $domain = $splitBase[1];
    $domain = rtrim($domain,'/ ');

    /* remove space around = sign */
    //$html = preg_replace('@(href|src)\s*=\s*@', '\1=', $html);
    $html = preg_replace('@(?<=href|src)\s*=\s*@', '=', $html);

    /* Fix google link weirdness */
    $html = str_ireplace('google.com/undefined', 'google.com', $html);

    /* add http to naked domain links so they'll be ignored later */
    $html = str_ireplace('a href="'.$domain, 'a href="http://'.$domain, $html);

    /* Standardize orthography of domain name */
    $html = str_ireplace($domain, $domain, $html);

    /* Correct base URL, if necessary */
    $server = preg_replace('@^([^\:]*)://([^/*]*)(/|$).*@', '\1://\2/', $base);

    /* Handle root-relative URLs */
    //$html = preg_replace('@\<([^>]*) (href|src)="/([^"]*)"@i', '<\1 \2="'.$server.'\3"', $html);
    $html = preg_replace('@\<([^>]*) (href|src)="/([^#"]*)"@i', '<\1 \2="' . $server . '\3"', $html);

    /* Handle base-relative URLs */
    //$html = preg_replace('@\<([^>]*) (href|src)="(?!http|mailto|sip|tel|callto|sms|ftp|sftp|gtalk|skype)(([^\:"])*|([^"]*:[^/"].*))"@i', '<\1 \2="'.$base.'\3"', $html);
    $html = preg_replace('@\<([^>]*) (href|src)="(?!#|http|mailto|sip|tel|callto|sms|ftp|sftp|gtalk|skype)(([^\:"])*|([^"]*:[^/"].*))"@i', '<\1 \2="' . $base . '\3"', $html);

    return $html;
}
```

**Comment by gadgetto** [comment]
Here is a little update to the `fullUrls` method which fixes a problem for the "add http to naked domain links so they'll be ignored later" part. This update respects the protocol of the base URL:

```
function fullUrls($base, $html) {
    /* Extract domain name from $base */
    $splitBase = explode('//', $base);
    $protocol = $splitBase[0];
    $domain = $splitBase[1];
    $domain = rtrim($domain, '/ ');

    /* remove space around = sign */
    //$html = preg_replace('@(href|src)\s*=\s*@', '\1=', $html);
    $html = preg_replace('@(?<=href|src)\s*=\s*@', '=', $html);

    /* Fix google link weirdness */
    $html = str_ireplace('google.com/undefined', 'google.com', $html);

    /* add base protocol to naked domain links so they'll be ignored later */
    $html = str_ireplace('a href="'.$domain, 'a href="'.$protocol.'//'.$domain, $html);

    /* Standardize orthography of domain name */
    $html = str_ireplace($domain, $domain, $html);

    /* Correct base URL, if necessary */
    $server = preg_replace('@^([^\:]*)://([^/*]*)(/|$).*@', '\1://\2/', $base);

    /* Handle root-relative URLs */
    //$html = preg_replace('@\<([^>]*) (href|src)="/([^"]*)"@i', '<\1 \2="'.$server.'\3"', $html);
    $html = preg_replace('@\<([^>]*) (href|src)="/([^#"]*)"@i', '<\1 \2="' . $server . '\3"', $html);

    /* Handle base-relative URLs */
    //$html = preg_replace('@\<([^>]*) (href|src)="(?!http|mailto|sip|tel|callto|sms|ftp|sftp|gtalk|skype)(([^\:"])*|([^"]*:[^/"].*))"@i', '<\1 \2="'.$base.'\3"', $html);
    $html = preg_replace('@\<([^>]*) (href|src)="(?!#|http|mailto|sip|tel|callto|sms|ftp|sftp|gtalk|skype)(([^\:"])*|([^"]*:[^/"].*))"@i', '<\1 \2="' . $base . '\3"', $html);

    return $html;
}
```

**Comment by gadgetto** [comment]
**And URLs to external sites should be ignored completely.**

**Comment by BobRay** [comment]
I refactored the fullUrl() code from the ground up, moved it to a class, and created a test file for it with 15 cases with all your test cases and a few more. The test says it works and I think it does everything you want, but I have no way to test it in action. 

Can you check it out for me?

It's in the dev branch.

You'll need the fullurls.class.php file in the model directory and the new version of the emailresource.class.php file in that same directory.

The test file is _build/test/testFulUrls.php if you want to play with it.

One question I still have. I've left no-protocol links alone (href='//externaldomain.com'), but I've read that some email clients will treat that as a link to a local file. The comments I read are a few year old. Do you know if it's now safe to use these?

FYI, when testing, using domain.com and externaldomain.com has problems since domain.com is part of externaldomain.com. I've changed it to localdomain.com and externaldomain.com.

**Comment by gadgetto** [comment]
I recently wrote a complete new method for generating full URLs using php's DOMDocument method (in conjunction with SmartDomDocument from here: http://beerpla.net/projects/smartdomdocument-a-smarter-php-domdocument-class/).

Its more stable and much more readable/configurable then using regex.

**BTW, here is an article why it isn't a good idea using regex to parse HTML:**
http://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags/1732454#1732454


```php
    /**
     * Replace URLs in HTML with full URLs
     * (works for "<a href" and "<img src" tags)
     *
     * @access private
     * @param string $base The base URL (needs trailing /)
     * @param string $html The unparsed HTML
     * @return mixed The parsed HTML as string or false
     */
    private function _fullURLs($base = null, $html = null) {
        if (empty($html) || empty($base)) { return false; }
        
        // Use the SmartDOMDocument extension
        if (!class_exists('SmartDOMDocument')) { return false; }
    
        $smartDOMDocument = new SmartDOMDocument();
        if (!($smartDOMDocument instanceof SmartDOMDocument)) {
            $this->modx->log(modX::LOG_LEVEL_ERROR, 'SmartDOMDocument class could not be instantiated.');
            return false;
        }
    
        $smartDOMDocument->loadHTML($html);
        
        // Process all link tags
        $elements = $smartDOMDocument->getElementsByTagName('a');
    
        foreach ($elements as $element){
            // Get the value of the href attribute
            $href = $element->getAttribute('href');
            
            // Check if we have a protocol-relative URL - if so, don't touch and continue!
            // Sample:  //www.domain.com/page.html 
            if (mb_substr($href, 0, 2) == '//') { continue; }
            
            // Remove leading / from relative URLs
            $href = ltrim($href, '/');
            
            // De-construct the UR(L|I)
            $url_parts = parse_url($href);
            
            // ['scheme']   - (string) https | http | ftp | ...
            // ['host']     - (string) www.domain.com
            // ['port']     - (int)    9090
            // ['user']     - (string) username
            // ['pass']     - (string) password
            // ['path']     - (string) section1/page1.html | /section1/page1.html
            // ['query']    - (string) all after ?
            // ['fragment'] - (string) all after text anchor #
            
            // Check if UR(L|I) is completely invalid - if so, don't touch and continue!
            if ($url_parts == false) { continue; }
            
            // Check if text anchor only - if so, don't touch and continue!
            // Sample: #textanchor
            if (!empty($url_parts['fragment']) && empty($url_parts['scheme']) && empty($url_parts['host']) && empty($url_parts['path'])) { continue; }
    
            // Finally add base URL to href value
            if (empty($url_parts['host'])) {
                $element->setAttribute('href', $base.$href);
            }
        }
    
        // Process all img tags
        $elements = $smartDOMDocument->getElementsByTagName('img');
        
        foreach ($elements as $element){
            // Get the value of the img attribute
            $href = $element->getAttribute('src');
            
            // Check if we have a protocol-relative URL - if so, don't touch and continue!
            // Sample:  //www.domain.com/page.html 
            if (mb_substr($href, 0, 2) == '//') { continue; }
            
            // Remove / from relative URLs
            $href = ltrim($href, '/');
            
            // De-construct the UR(L|I)
            $url_parts = parse_url($href);
    
            // Check if UR(L|I) is completely invalid - if so, don't touch and continue!
            if ($url_parts == false) { continue; }
            
            // Finally add base URL to href value
            if (empty($url_parts['host'])) {
                $element->setAttribute('src', $base.$href);
            }
        }
            
        // Return the processed (X)HTML
        return $smartDOMDocument->saveHTMLExact();
    }
```

**Comment by gadgetto** [comment]
Nevertheless I'll try to test your new method. And thanks for your effort!

**Comment by jdpierce** [comment]
Hi Bob,
This issue appears to affect mailto and phone links as well. The regex is a bit much for me but if we can sort out a fix I'll pass it along. Thanks for your work on this too!

**Comment by BobRay** [comment]
Rats. IIRC, the original regex had those covered, but I removed them to simplify it. :(

**Comment by BobRay** [comment]
@jdpierce: I was wrong, the original regex covered file and ftp links. How would this affect mail or phone links? Neither would contain a URL. and both should already be complete and ignored by ER. Can you give an example of what you mean.

**Comment by jdpierce** [comment]
Sure thing. If you look at: http://www.linfield.edu/academic-affairs/academic-affairs-newsletter/may-2-2017-academic-affairs-weekly.html (an internal weekly newsletter), you'll see the mailto links are formatted correctly in the source code (<a href="mailto:..."). However, if I preview the same file when logged in to manager or send a test email of the resource, the mailto links are formatted <a href="https://www.linfield.edu/mailto:... I can forward a copy of the email to you if you would like. BTW, it's good to meet you. Your Modx book has been on my shelf for a few years now!

**Comment by BobRay** [comment]
Try adding this code to the fullurls.class.php file just below line 80

line 80:   foreach ($tags as $tag) {

```
            if (preg_match('/mailto:|tel:/)', $tag) === 1) {
                  return $html;
            }
```

**Comment by jdpierce** [comment]
I added the code as follows:
foreach ($tags as $tag) {
			 if (preg_match('/mailto:|tel:/)', $tag) === 1) {
                  return $html;
            }

            $fullTag = $tag;
            if ($debug) {
                echo "\nFullTag: " . $fullTag;
            }
I'm afraid the problem is still there. No change in behavior.

**Comment by BobRay** [comment]
Oops, - typo. Try this:

if (preg_match('/mailto:|tel:/'), $tag) === 1) {

**Comment by jdpierce** [comment]
Drop the 3rd parenthesis and it works!
if (preg_match('/mailto:|tel:/', $tag) === 1) {

Problem solved. Thank you sir!

**Comment by BobRay** [comment]
Thanks. When will I learn to put code in my code editor before posting it. ;)

**Comment by BobRay** [comment]
Sorry, not firing in all cylinders today. Replace 

`return $html`

in the code above with:

`continue;`

**Comment by jdpierce** [comment]
No worries.
It tests fine with the change below too. Have a good weekend.
